# Generated by Django 2.2 on 2019-03-11 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('username', models.CharField(default='', max_length=70)),
                ('password1', models.CharField(default='', max_length=200)),
                ('password2', models.CharField(default='', max_length=200)),
                ('email_address', models.EmailField(default='', max_length=254)),
                ('profile_picture', models.CharField(default='', max_length=800)),
                ('userForeignKey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=1000)),
                ('recipe_ingredients', models.CharField(default='', max_length=3000)),
                ('recipe_directions', models.CharField(default='', max_length=3000)),
                ('date_created', models.DateField()),
                ('recipe_creator', models.CharField(default='', max_length=60)),
                ('recipe_image', models.CharField(default='', max_length=800)),
                ('recipeForeignKey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mini5App.LoginModel')),
            ],
        ),
    ]
